version: '3'

services:
  node:
    image: node:10-slim
    user: 1000:1000
    working_dir: /app
    volumes:
      - ./:/app
  minecraft-version-packager:
    image: node:10-slim
    user: 1000:1000
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: node src/index.js